default:
  - serve
build:dev:
  - lint
  - dust
  - less
build:dist:
  - clean
  - build:dev
  - requirejs
  - copy
serve:
  - build:dev
  - browserSync:dev
  - watch
serve:dist:
  - build:dist
  - browserSync:dist
  - watch:dist
lint:
  - eslint
